package leetCode
// You are given two strings s and t.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Return the letter that was added to t.

class FindTheDifference389 {
    fun find(inputS: String, inputT: String): Char {
        var frequencyMap = mutableMapOf<Char, Int>()

        inputS.forEach { letter ->
            frequencyMap[letter] = frequencyMap.getOrDefault(letter, 0) + 1
        }

        inputT.forEach { letter ->
            if (frequencyMap.getOrDefault(letter, 0) == 0){
                return letter
            }
            frequencyMap[letter] = frequencyMap.getOrDefault(letter, 0) - 1
        }
        return ' '
    }
}